import React, { useEffect, useState } from 'react';
import { useNavigate, useSearchParams, useLocation } from 'react-router-dom';
import { socketService } from '../../services/socket.service';
import { getTimeControl } from '../../types/timeControl';

const MatchmakingWaiting: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const [searchParams] = useSearchParams();
  const tcKey = searchParams.get('tc') ?? '600+0';
  const timeControl = getTimeControl(tcKey);

  const [userId] = useState(() => `player-${Math.random().toString(36).substr(2, 9)}`);
  const [dots, setDots] = useState('');
  const [waitSeconds, setWaitSeconds] = useState(0);

  const [isAllowed, setIsAllowed] = useState(false);
  const validatedRef = React.useRef(false); // to avoid double mm_flow consumption (if the page rerender or triggers two times useEffect[[location.state, navigate, tcKey]])

  // This effect validates the "mm_flow" and the "mm_token" generated by the gamemode page's [Start] buttons.
  useEffect(() => {
    if (validatedRef.current) return;
    const nav = location.state as { fromGameMode?: boolean; mm_token?: string } | null;
    const raw = sessionStorage.getItem('mm_flow');

    if (!nav?.fromGameMode || !nav.mm_token || !raw) {
      console.log("DEBUG : ❌ No mm_token or invalid access to matchmaking.");
      navigate('/gamemode');
      return;
    }
    try {
      const parsed = JSON.parse(raw) as { mm_token: string; tcKey: string; ts: number };
      const toOld = Date.now() - parsed.ts > 2000; //2s - validity time for the token (changeable)
      const tokenMismatch = nav.mm_token !== parsed.mm_token || parsed.tcKey !== tcKey;

      if (toOld || tokenMismatch) {
        console.log("DEBUG : ❌ Flow mm_token expired or invalid.");
        sessionStorage.removeItem('mm_flow');
        navigate('/gamemode', { replace: true });
        return;
      }
      validatedRef.current = true;
      sessionStorage.removeItem('mm_flow');
      console.log('DEBUG : ✅ Matchmaking flow token validated successfully.');
      setIsAllowed(true);
    } catch (error) {
      sessionStorage.removeItem('mm_flow');
      navigate('/gamemode');
    }
  }, [location.state, navigate, tcKey]);

  useEffect(() => {
    const dotInterval = setInterval(() => {
      setDots(d => d.length >= 3 ? '' : d + '.');
    }, 500);
    const timeInterval = setInterval(() => setWaitSeconds(s => s + 1), 1000);
    return () => { clearInterval(dotInterval); clearInterval(timeInterval); };
  }, []);

  useEffect(() => {
    if (!isAllowed) return;

    socketService.connect(userId);

    const doMatchmaking = () => {
      socketService.on('matchmaking:found', (data: { gameId: string; role: 'white' | 'black' }) => {
        //beboccas: I may use the same system or even the same flow with different UUID without time check to avoid unauthorized access to the game page
        navigate(`/game/${data.gameId}`, {
          state: { userId, role: data.role, tcKey },
        });
      });
      socketService.joinMatchmaking(tcKey);
    };

    if (socketService.isConnected()) {
      doMatchmaking();
    } else {
      socketService.on('connect', doMatchmaking);
    }

    return () => {
      socketService.off('matchmaking:found');
      socketService.off('matchmaking:cancelled');
      socketService.cancelMatchmaking();
    };
  }, [isAllowed, userId, tcKey, navigate]);

  const handleCancel = () => {
    socketService.cancelMatchmaking();
    navigate('/gamemode');
  };

  return (
    <div className="min-h-screen bg-background-light flex items-center justify-center font-body">
      <div className="bg-white rounded-2xl shadow-xl border border-accent/30 p-10 max-w-sm w-full text-center flex flex-col items-center gap-6">
        {/* anim chess piece spnning */}
        <div className="relative w-16 h-16">
          <div className="absolute inset-0 rounded-full border-4 border-accent/20 animate-spin border-t-primary" />
          <span className="absolute inset-0 flex items-center justify-center text-3xl select-none">
            ♟
          </span>
        </div>

        <div>
          <h2 className="text-2xl font-heading font-bold text-text-dark mb-1">
            Finding Opponent{dots}
          </h2>
          <p className="text-sm text-text-dark/60">
            Time contol: <span className="font-smibold text-primary">{timeControl.label}</span>
          </p>
        </div>

        <button
          onClick={handleCancel}
          className="w-full py-2.5 rounded-lg border-2 border-primary/40 text-primary font-semibold text-sm hover:bg-primary/5 transition-colors">
          Cancel
        </button>
      </div>
    </div>
  );
};

export default MatchmakingWaiting;
